name: hse
description: Private Office UCO

version: 1.0.9


environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.17.0
  responsive_builder: ^0.2.0+2
  provider: ^4.0.5+1
  get: ^3.24.0
  #charts_flutter: ^0.9.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  getflutter: ^1.0.11
  permission_handler: ^5.0.1+1
  uuid: ^2.0.4
  font_awesome_flutter: ^8.7.0
  universal_html: ^1.2.3
  google_fonts: ^1.1.1
  pin_code_view: ^0.2.1
  google_maps_flutter: ^0.5.25+1
  flutter_google_maps: ^3.6.0
  location: ^2.5.4
  url_launcher: ^5.4.2
  #  barcode_scan: ^2.0.1
  table_calendar: ^2.2.3
  flutter_launcher_icons: ^0.8.1
  version: ^1.2.0
  easy_web_view: ^1.3.1
  native_pdf_view: ^3.9.0

  flutter_plugin_pdf_viewer: ^1.0.7
  step_progress_indicator: ^0.2.1+4
  smooth_page_indicator: ^0.1.5
  kinfolk: ^1.0.1
  #video_player: ^1.0.1
  fl_chart: ^0.12.0
  downloads_path_provider: ^0.1.0
  #  flt_telephony_info: any
  mobile_number: ^1.0.2
  image_picker: ^0.6.7+22
  cached_network_image: ^2.0.0
  open_file: ^3.0.3
  cupertino_icons: ^0.1.3
  flutter_local_notifications: ^4.0.1+2
  qr_code_scanner: ^0.3.5
  firebase_auth: ^0.18.1+2
  firebase_messaging: ^6.0.13
  firebase_crashlytics: ^0.2.1+1
  firebase_core: ^0.5.0+1

dependency_overrides:
  path: 1.7.0
  flutter_svg: ^0.18.0
  path_provider: ^1.6.5
  #chewie: ^0.10.0
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.2

flutter_icons:
  image_path: "assets/icon/logo1.png"

  android: "launcher_icon"
  ios: true

flutter:


  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/fake/

  fonts:
    - family: SourceSansPro ExtraLight
      fonts:
        - asset: fonts/SourceSansPro-ExtraLight.ttf
          weight: 200

    - family: SourceSansPro Light
      fonts:
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 300

    - family: SourceSansPro Regular
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 400

    - family: SourceSansPro SemiBold
      fonts:
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
flutter_intl:
  enabled: true
